# Generated by Django 6.0.3 on 2026-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_date_of_birth_user_purpose_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
